config/routes.rb
Rails.application.routes.draw do


  resources :audit_logs
  resources :company_banks
  resources :admin_watchdogs
  resources :admin_logins
  resources :selfie_verifications,:except => [:new, :create]
  resources :address_verifications,:except => [:new, :create]
  resources :nationalid_verifications,:except => [:new, :create]
  resources :user_infos
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      resources :cards_logs
      resources :cards_categories
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card" 
      get "cards_status" => "cards#cards_status"
      get "admin_add_note" => "cards#admin_add_note"
      post "admin_add_note" => "cards#admin_add_note"
      get "send_card" => "cards#send_card"
      post "send_card" => "cards#send_card"
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      get "user_addresses" => "addresses#user_addresses"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :wallets_transfer_ratios
      resources :user_wallets
      resources :sms_logs
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :bank_accounts
      resources :ticket_departments
      resources :tickets
      get 'tickets/:id/replies' => 'tickets#showreplies'
      post 'tickets/reply' => 'tickets#create_reply'
      resources :withdraws
      resources :payers_blogs
      get "users_blogs" => "payers_blogs#users_blogs"
      get "catblogs" => "payers_blogs#catblogs"
      get "display_blog" => "payers_blogs#display_blog"
      get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
      get "payers_blogs_categories" => "payers_blogs#payers_blogs_categories"

    end
  end

  resources :withdraws
  resources :admins,:except => [:new]
  resources :affilate_programs
  resources :countries
  resources :logins
  resources :verifications
  resources :watchdogs
  resources :users,:except => [:new]
  root "admins#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "admins#unlockaccount"
  get "two_factor" => "admins#get_two_factor"
  post "two_factor" => "admins#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "audit_log" => "audit_logs#user_audit_log"
  get "admin_log" => "admin_watchdogs#admin_log"
  get "statistics" => "admins#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "active_sessions" => "logins#active_sessions"
  get "admin_active_sessions" => "admin_logins#admin_active_sessions"
  get "send_confirmation_email" => "admins#send_confirmation_email"
  get "change_confirmation_code" => "admins#change_confirmation_code"
  get "confirm_google_code" => "admins#confirm_google_code"
  #get "affilate-program/:refered_by" => "affilate_programs#send_invitation"
  #post "send_invitation_email" => "affilate_programs#send_invitation_email"
  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "admins#add_admin"
  post "add_admin" => "admins#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "admin_logins#lock_page"
  post "lock_page" => "admin_logins#check_to_unlock"
  resources :cards_logs
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "admin_add_note" => "cards#admin_add_note"
  post "admin_add_note" => "cards#admin_add_note"
  get "send_card" => "cards#send_card"
  post "send_card" => "cards#send_card"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_addresses" => "addresses#user_addresses"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "wallets_status" => "user_wallets#wallets_status"
  get "user_list_data" => "user_wallets#user_list_data"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "admin_add_balance" => "user_wallets#admin_add_balance"
  post "admin_add_balance_post" => "user_wallets#admin_add_balance_post"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :users_wallets_transfers
  resources :sms_logs
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  resources :uploads
  resources :money_ops
  get "operations_status" => "money_ops#operations_status"
  get "remittance_operations" => "money_ops#remittance_operations"
  resources :bank_accounts
  resources :ticket_departments
  get 'tickets/statistics' => 'tickets#statistics'
  resources :tickets
  post 'tickets/reply' => 'tickets#create_reply'
  
  

  get "user_bank_accounts" => "withdraws#user_bank_accounts"
  get "close_ticket" => "tickets#close_ticket"
  
  resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

  resource :session,
      controller: 'clearance/sessions',
      only: [:create]

  resources :admins,
      controller: 'admins',
      only: Clearance.configuration.user_actions do
        resource :password,
          controller: 'clearance/passwords',
          only: [:create, :edit, :update]
      end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  if Clearance.configuration.allow_sign_up?
   get '/sign_up' => 'admins#new', as: 'sign_up'
  end
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
    has_one_attached :payment_receipt
    validates_uniqueness_of :number
    validate :check_value
    validate :check_expiration
    before_save :default_values
    validates :value, numericality: { only_integer: true }
    validates :status, numericality: { only_integer: true }
    has_many :cards_log , foreign_key: "card_id"
    belongs_to :user , foreign_key: "user_id" , optional: true

    def default_values
        self.number ||= [*('0'..'9'),*('a'..'z')].to_a.shuffle[0,16].join
        self.invoice_id ||= 0
    end

    def check_value
      errors.add(:value, "must be equal or greater than 5 USD") if value == nil || value < 5
    end

    def check_expiration
        errors.add(:expired_at, "Must be at least two days from now") if expired_at < Date.today + 2.days
    end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status,options_for_select([['Active',1],['Charged',2],['pending',3],['disabled',4]]),  {}, {} %>
  </div>

  <div class="field">
    <%= form.label :expired_at %>
    <%= form.date_select :expired_at %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.number_field :invoice_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/cards_status.html.erb
<%# debug(@card_status.status)%>
<%# debug(params[:id])%>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= form_with(model: @card, local: true) do |form| %>
    <% if @card.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>
  
        <ul>
        <% @card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <p>
      <strong>Card Number:</strong>
      <%= @card.number.scan(/.{1,4}/).join('-') %>
      </p>
    </div>

    <div class="field">
    <p>
    <strong>User:</strong>
    <%= @card.user.firstname + " " + @card.user.lastname %>
    </p>
    </div>
  
    <div class="field">
      <%= form.label :value %>
      <%= form.number_field :value %>
    </div>
  
    <div class="field">
      <%= form.label :status %>
      <%= form.select :status,options_for_select([['Active',1],['Charged',2],['pending',3],['disabled',4]], :selected => @card.status),  {}, {} %>
    </div>
  
    <div class="field">
      <%= form.label :expired_at %>
      <%= form.date_select :expired_at %>
    </div>
  
    <div class="field">
      <%= form.label :invoice_id %>
      <%= form.number_field :invoice_id %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t('cards.cards') %></h1>

    <%= form_tag  url_for(:controller => 'cards', :action => 'search'), :method => 'get' do %>

        <div>
            <div>
                 <div>
                     <div >
                       <div style="width:40%; height:180px; background:#f6f2f1; box-shadow: 0 0 8px #ccc; margin-bottom:20px;">
                         <div>
                           <div>
                           <input type="text" name="search"  placeholder="Search about something" >
                           <br><br><%= t('user name') %> <input type="text" name="search_user"  placeholder="Search for a spacific user" >
                           <div  style="margin-top:20px;">
                               <%= t('card status') %>
                              <%= select_tag :status,options_for_select([['Active',1],['Charged',2],['pending',3],['disabled',4]]), {:include_blank => 'select status'} %>
                            
                              <br><h4><%= t('Expiration Date') %>:</h4>
                              <%= t('From') %> <%= date_field_tag :searchdatefrom %>
                              <%= t('To') %> <%= date_field_tag :searchdateto %>
                             </div>
                            <div style="margin-top:20px;">
                                <button type="submit" ><%= t('search') %> </button>
                            </div>
                           </div>
                         </div>
                       </div>
                     </div>
                 </div>
            </div>
        </div>
      <% end %>
<br><br>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Number</th>
      <th>Value</th>
      <th>Status</th>
      <th>Expired at</th>
      <th>Operation ID</th>
      <th>Invoice</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <% if card.user_id != 0 %>
        <td><%= card.user.firstname + " " + card.user.lastname %></td>
        <% else %>
        <td><%= "-" %></td>
        <% end %>
        <% if card.status == 3 %>
        <td><%= "****-****-****-****" %></td>
        <% else %>
        <td><%= card.number.scan(/.{1,4}/).join('-') %></td>
        <% end %>
        <td><%= card.value %></td>
        <% if card.status == 1 %>
        <td><%= "Active" %></td>
        <% elsif card.status == 2 %>
        <td><%= "Charged" %></td>
        <% elsif card.status == 3 %>
            <td><%= "pending" %></td>
        <% elsif card.status == 4 %>
            <td><%= "disabled" %></td>
        <% end %>
        <td><%= card.expired_at %></td>
        <td><%= card.operation_id %></td>
        <td><%= card.invoice_id %></td>
        <% if card.status == 4 %>
        <td><a href="/cards_status?id=<%= card.id %>" class="btn btn-primary">push to enable</a></td>
        <% else %>
        <td><a href="/cards_status?id=<%= card.id %>" class="btn btn-primary">push to disable</a></td>
        <% end %>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New Card', new_card_path %></button>

app/views/cards/new.html.erb
<div class="padding">
    <div class="box">
        <div class="box-header">
             <h2>New Card</h2>
        </div>
        <div class="box-divider m-0"></div>
            <div class="box-body">
                <%= form_with(model: @card, local: true) do |form| %>
                    <% if @card.errors.any? %>
                         <div id="error_explanation">
                             <%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved: 
                             <ul>
                                <% @card.errors.full_messages.each do |message| %>
                                   <li><%= message %></li>
                                <% end %>
                             </ul>
                         </div>
                    <% end %>

                        <div class="form-group row">
                            <label class="col-sm-2 form-control-label">Card Type</label>
                            <div class="col-sm-10">
                            <%= form.select :card_type,options_for_select([['For spacific user',1],['For spacific country',2]]),  {:include_blank => "Select Card Type"}, {:class => 'form-control c-select' , :id => "cardtype" , :required => true } %>
                            </div>
                        </div>

                        <div class="form-group row" id="country" style="display:none;" >
                            <label class="col-sm-2 form-control-label">Country</label>
                            <div class="col-sm-10">
                            <%= form.select :country_id, Country.all.collect {|p| [ p.Full_Name, p.id ] },{}, {  class: 'form-control c-select' , id: "countryid" }  %>
                            </div>
                        </div>

                        <div class="form-group row" id="usercard" style="display:none;">
                            <label class="col-sm-2 form-control-label">User</label>
                            <div class="col-sm-10">
                                <%= form.text_field :user_id,  class: 'form-control' , :required => true , placeholder: "User Email or Account number" , :id => "userid" %>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 form-control-label">Card Value</label>
                            <div class="col-sm-10">
                                <%= form.text_field :value,  class: 'form-control' , :required => true %>
                            </div>
                        </div>

                        <div class="form-group row" id="cardstatus" style="display:none;">
                            <label class="col-sm-2 form-control-label">Status</label>
                            <div class="col-sm-10">
                            <%= form.select :status,options_for_select([['Active',1],['Charged',2],['pending',3]]),  {}, {:class => 'form-control c-select'} %>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 form-control-label">Expireed At</label>
                            <div class="col-sm-10">
                                <%= form.date_select :expired_at , :class => 'form-control' %>
                            </div>
                        </div>

                       <div class="form-group row m-t-md">
                           <div class="col-sm-offset-2 col-sm-10">
                               <button type="submit" class="btn btn-fw primary" id="submit" >Submit</button>
                           </div>
                       </div>
                <% end %>
            </div>
            
    </div>
    <%= link_to 'Back', cards_path %>
</div>
<script src="/js/jquery-3.3.1.min.js"></script>
<script>

        $(document).ready(function() {

            $("#cardtype").change(function() {
                var selectedtype = $( "#cardtype option:selected" ).val();
                //console.log(selectedtype)
                if (selectedtype == 1){
                    $('#countryid').val(0);
                    $('#usercard').show();
                    $('#country').hide();
                    $('#cardstatus').show();               
                }else if (selectedtype == 2){
                    $('#userid').val(0);
                    $('#usercard').hide();
                    $('#country').show();
                    $('#cardstatus').hide(); 
                }
            });

        });
        
</script>

app/views/cards/search.html.erb
<section >
<%= form_tag  url_for(:controller => 'cards', :action => 'search'), :method => 'get' do %>

  <div>
      <div>
           <div>
               <div >
                 <div style="width:40%; height:180px; background:#f6f2f1; box-shadow: 0 0 8px #ccc; margin-bottom:20px;">
                   <div>
                     <div>
                     <input type="text" name="search"  placeholder="Search about something" >
                     <br><br><%= t('user name') %> <input type="text" name="search_user"  placeholder="Search for a spacific user" >
                     <div  style="margin-top:20px;">
                         <%= t('card status') %>
                        <%= select_tag :status,options_for_select([['Active',1],['Charged',2],['pending',3],['disabled',4]]), {:include_blank => 'select status'} %>
                      
                        <br><h4><%= t('Expiration Date') %>:</h4>
                        <%= t('From') %> <%= date_field_tag :searchdatefrom %>
                        <%= t('To') %> <%= date_field_tag :searchdateto %>
                       </div>
                      <div style="margin-top:20px;">
                          <button type="submit" ><%= t('search') %> </button>
                      </div>
                     </div>
                   </div>
                 </div>
               </div>
           </div>
      </div>
  </div>
<% end %>
<br><br>

 <table>
  <thead>
    <tr>
       <th style="color:#363669 !important;">Username</th>
       <th style="color:#363669 !important;">Number</th>
       <th style="color:#363669 !important;">Value</th>
       <th style="color:#363669 !important;">Status</th>
       <th style="color:#363669 !important;">Expired at</th>
       <th style="color:#363669 !important;">Operation ID</th>
       <th style="color:#363669 !important;"><%= t('created at') %></th>
       <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>

    <% @Cards.each do |card| %>
   
      <tr>
        <td><%= card.user.firstname + " " + card.user.lastname %></td>
        <% if card.status == 3 %>
        <td><%= "****-****-****-****" %></td>
        <% else %>
        <td><%= card.number.scan(/.{1,4}/).join('-') %></td>
        <% end %>
        <td><%= card.value %></td>
        <% if card.status == 1 %>
        <td><%= "Active" %></td>
        <% elsif card.status == 2 %>
        <td><%= "Charged" %></td>
        <% elsif card.status == 3 %>
            <td><%= "pending" %></td>
        <% elsif card.status == 4 %>
            <td><%= "disabled" %></td>
        <% end %>
        <td><%= card.expired_at %></td>
        <td><%= card.operation_id %></td>
        <td><%= card.created_at %></td>
        <td><%= link_to 'Show', card %></td>
      </tr>
      <% end %>
  </tbody>
</table>
<br>
</section>

app/views/cards/searchpost.html.erb
<%# debug(params)%>

app/views/cards/show.html.erb
<div class="padding">
  
      <div class="box">
        <div class="box-header">
          <h3>Card Details</h3>
        </div>
        <table class="table">
          <thead>
          <% if @card.user_id != 0 %>
            <tr>
            <th>Username</th>
            <td><%= @card.user.firstname + " " +  @card.user.lastname   %></td>
            </tr>
          <% end %>
          </thead>
          <tbody>
            <tr>
              <th>Number</th>
              <td>  <% if @card.status == 3 %>
              <%= "****-****-****-****" %>
              <% else %>
              <%= @card.number.scan(/.{1,4}/).join('-') %>
              <% end %></td>
            </tr>
            <tr>
              <th>Value</th>
              <td> <%= @card.value %></td>
            </tr>
            <tr>
              <th>Status</th>
              <td>  <% if @card.status == 1 %>
              <%= "Active" %>
                <% elsif @card.status == 2 %>
                <%= "Charged" %>
                <% elsif @card.status == 3 %>
                <%= "pending" %>
                <% elsif @card.status == 4 %>
                <%= "disabled" %>
                <% end %></td>
            </tr>
            <tr>
              <th>Expired at:</th>
              <td> <%= @card.expired_at %></td>
            </tr>
            <% if @card.operation_id != nil %>
            <tr>
              <th>Operation Id</th>
              <td> <%= @card.operation_id %></td>
            </tr>
            <% end %>
            <tr>
              <th>Card Type</th>
              <td>  <% if @card.card_type == 1 %>
              <%= "For spacific user" %>
            <% elsif @card.card_type == 2 %>
              <%= "For spacific country" %>
            <%# elsif @card.card_type == 3 %>
              <%# "Public" %>
            <% end %></td>
            </tr>
            <% if @card.card_type == 2 %>
            <tr>
              <th>Country</th>
              <td> <%= Country.where(id:@card.country_id).pluck(:Full_Name).first %></td>
            </tr>
            <% end %> 
            <tr>
            <th>Invoice ID</th>
            <td> <%= @card.invoice_id %></td>
            </tr>
            <% if @card.note != nil %>  
            <tr>
            <th>Note</th>
            <td> <%= @card.note %></td>
            </tr>  
            <% end %>     
          </tbody>
        </table>
        <% if @card.card_type == 2 && @card.status == 1  && @card.note == nil %>
        <div class="box-body">
        <%= form_for :send_card ,:url => send_card_path,:html => { :multipart => true } do |f| %>
              <%=  f.hidden_field :card_number, :value => @card.number.scan(/.{1,4}/).join('-') %>
              <%=  f.hidden_field :card_value, :value => @card.value %>
              <%=  f.hidden_field :card_id, :value => @card.id %>
              <div class="form-group row">
                  <label class="col-sm-2 form-control-label">Send This Card To a User</label>
                  <div class="col-sm-10">
                      <%= f.text_field :user_email , class: 'form-control' , :required => true , :placeholder => 'Add User Email Here' %>
                  </div>
              </div>

              <div class="form-group row">
                  <label class="col-sm-2 form-control-label">Send a Message With This Card</label>
                  <div class="col-sm-10">
                      <%= f.text_area :admin_msg , class: 'form-control' , :required => true , :placeholder => 'Add Message Here' %>
                  </div>
              </div>

              <div class="form-group row m-t-md">
                  <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-fw primary" id="submit" >Submit</button>
                  </div>
              </div>
        <% end %>
      </div>
      <% end %>
    </div>
      
<%= link_to 'Back', cards_path %>
</div>