config/routes.rb
Rails.application.routes.draw do


  resources :audit_logs
  resources :company_banks
  resources :admin_watchdogs
  resources :admin_logins
  resources :selfie_verifications,:except => [:new, :create]
  resources :address_verifications,:except => [:new, :create]
  resources :nationalid_verifications,:except => [:new, :create]
  resources :user_infos
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      resources :cards_logs
      resources :cards_categories
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card" 
      get "cards_status" => "cards#cards_status"
      get "admin_add_note" => "cards#admin_add_note"
      post "admin_add_note" => "cards#admin_add_note"
      get "send_card" => "cards#send_card"
      post "send_card" => "cards#send_card"
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      get "user_addresses" => "addresses#user_addresses"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :wallets_transfer_ratios
      resources :user_wallets
      resources :sms_logs
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :bank_accounts
      resources :ticket_departments
      resources :tickets
      get 'tickets/:id/replies' => 'tickets#showreplies'
      post 'tickets/reply' => 'tickets#create_reply'
      resources :withdraws
      resources :payers_blogs
      get "users_blogs" => "payers_blogs#users_blogs"
      get "catblogs" => "payers_blogs#catblogs"
      get "display_blog" => "payers_blogs#display_blog"
      get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
      get "payers_blogs_categories" => "payers_blogs#payers_blogs_categories"

    end
  end

  resources :withdraws
  resources :admins,:except => [:new]
  resources :affilate_programs
  resources :countries
  resources :logins
  resources :verifications
  resources :watchdogs
  resources :users,:except => [:new]
  root "admins#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "admins#unlockaccount"
  get "two_factor" => "admins#get_two_factor"
  post "two_factor" => "admins#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "audit_log" => "audit_logs#user_audit_log"
  get "admin_log" => "admin_watchdogs#admin_log"
  get "statistics" => "admins#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "active_sessions" => "logins#active_sessions"
  get "admin_active_sessions" => "admin_logins#admin_active_sessions"
  get "send_confirmation_email" => "admins#send_confirmation_email"
  get "change_confirmation_code" => "admins#change_confirmation_code"
  get "confirm_google_code" => "admins#confirm_google_code"
  #get "affilate-program/:refered_by" => "affilate_programs#send_invitation"
  #post "send_invitation_email" => "affilate_programs#send_invitation_email"
  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "admins#add_admin"
  post "add_admin" => "admins#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "admin_logins#lock_page"
  post "lock_page" => "admin_logins#check_to_unlock"
  resources :cards_logs
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "admin_add_note" => "cards#admin_add_note"
  post "admin_add_note" => "cards#admin_add_note"
  get "send_card" => "cards#send_card"
  post "send_card" => "cards#send_card"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_addresses" => "addresses#user_addresses"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "wallets_status" => "user_wallets#wallets_status"
  get "user_list_data" => "user_wallets#user_list_data"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "admin_add_balance" => "user_wallets#admin_add_balance"
  post "admin_add_balance_post" => "user_wallets#admin_add_balance_post"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :users_wallets_transfers
  resources :sms_logs
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  resources :uploads
  resources :money_ops
  get "operations_status" => "money_ops#operations_status"
  get "remittance_operations" => "money_ops#remittance_operations"
  resources :bank_accounts
  resources :ticket_departments
  get 'tickets/statistics' => 'tickets#statistics'
  resources :tickets
  post 'tickets/reply' => 'tickets#create_reply'
  
  

  get "user_bank_accounts" => "withdraws#user_bank_accounts"
  get "close_ticket" => "tickets#close_ticket"
  
  resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

  resource :session,
      controller: 'clearance/sessions',
      only: [:create]

  resources :admins,
      controller: 'admins',
      only: Clearance.configuration.user_actions do
        resource :password,
          controller: 'clearance/passwords',
          only: [:create, :edit, :update]
      end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  if Clearance.configuration.allow_sign_up?
   get '/sign_up' => 'admins#new', as: 'sign_up'
  end
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/money_op.rb
class MoneyOp < ApplicationRecord
    validates_uniqueness_of :opid
    before_save :default_values
    belongs_to :user ,:foreign_key => "user_id"

    # Add default value to opid before save
    def default_values
        self.opid ||= "PY"+[*('A'..'Z'),*('0'..'9')].to_a.shuffle[0,10].join
    end
end

app/controllers/money_ops_controller.rb
class MoneyOpsController < ApplicationController
  before_action :set_money_op, only: [:show]

  # GET list of Money Operations and display it
  # @return [id] Money Operation unique ID (Created automatically).
  # @return [opid] Operation unique number  (Created automatically and must be 12 digits and letters ).
  # @return [optype] Operation type (1 for Sent & 2 for Receive).
  # @return [amount] Operation amount.
  # @return [payment_gateway] Operation payment gateway (paypal,bitcoin,...).
  # @return [status] Operation status (0 for pending & 1 for compeleted).
  # @return [payment_date] Payment operation creation date.
  # @return [payment_id] Payment ID for the operation itself.
  # @return [user_id] Operation user id.
  # @return [created_at] Date created.
  # @return [updated_at] Date Updated.
  def index
    @money_ops = MoneyOp.all
  end

  # GET a spacific Money Operation and display it
  # @param [Integer] id Money operation unique ID.
  # @return [opid] Operation unique number (Created automatically and must be 12 digits and letters ).
  # @return [optype] Operation type (1 for Sent & 2 for Receive).
  # @return [amount] Operation amount.
  # @return [payment_gateway] Operation payment gateway (paypal,bitcoin,...).
  # @return [status] Operation status (0 for pending & 1 for compeleted).
  # @return [payment_date] Payment operation creation date.
  # @return [payment_id] Payment ID for the operation itself.
  # @return [user_id] Operation user id.
  # @return [created_at] Date created.
  # @return [updated_at] Date Updated.
  def show
    @bank_type = ""
    if set_money_op.optype == 4
      @remittance_data = Card.where("operation_id = ?",set_money_op.opid).first
      @bank = CompanyBank.where("bank_key = ?",set_money_op.payment_gateway).first
      @bank_type = @bank.bank_category.to_s
    end
  end

  # GET a new Money Operation
  # @param [Integer] id Money operation unique ID (Created automatically).
  # @param [String] opid Operation unique number (Created automatically and must be 12 digits and letters ).
  # @param [Integer] optype Operation type (1 for Sent & 2 for Receive).
  # @param [Integer] amount Operation amount.
  # @param [Integer] payment_gateway Operation payment gateway (paypal,bitcoin,...).
  # @param [Integer] status Operation status (0 for pending & 1 for compeleted).
  # @param [Date] payment_date Payment operation creation date.
  # @param [Integer] payment_id Payment ID for the operation itself.
  # @param [Integer] user_id Operation user id.
  def new
    @money_op = MoneyOp.new
  end

  # POST a new Money Operation and save it
  # @return [id] Money Operation unique ID (Created automatically).
  # @return [opid] Operation unique number (Created automatically and must be 12 digits and letters ).
  # @return [optype] Operation type (1 for Sent & 2 for Receive).
  # @return [amount] Operation amount.
  # @return [payment_gateway] Operation payment gateway (paypal,bitcoin,...).
  # @return [status] Operation status (0 for pending & 1 for compeleted).
  # @return [payment_date] Payment operation creation date.
  # @return [payment_id] Payment ID for the operation itself.
  # @return [user_id] Operation user id.
  # @return [created_at] Date created.
  # @return [updated_at] Date Updated.
  def create

    @money_op = MoneyOp.new(money_op_params)

    respond_to do |format|
      if @money_op.save
        format.html { redirect_to @money_op, notice: 'Money op was successfully created.' }
        format.json { render :show, status: :created, location: @money_op }
      else
        format.html { render :new }
        format.json { render json: @money_op.errors, status: :unprocessable_entity }
      end
    end
  end


  # Change Money Operations status
  # @param [Integer] id Money Operation unique ID (Created automatically).
  # @param [Integer] status Money Operation status (0 for Pending, 1 for Compeleted).
  # @return [id] Money Operation unique ID (Created automatically).
  # @return [opid] Operation unique number (Created automatically and must be 12 digits and letters ).
  # @return [optype] Operation type (1 for Sent & 2 for Receive, 3 for withdraw , 4 for remittance).
  # @return [amount] Operation amount.
  # @return [payment_gateway] Operation payment gateway (paypal,bitcoin,...).
  # @return [status] Operation status (0 for pending & 1 for compeleted).
  # @return [payment_date] Payment operation creation date.
  # @return [payment_id] Payment ID for the operation itself.
  # @return [user_id] Operation user id.
  # @return [created_at] Date created.
  # @return [updated_at] Date Updated.
  def operations_status

    @operations_status = MoneyOp.where(:id => params[:id].to_i).first
    @operation_card = Card.where(:operation_id => @operations_status.opid).first
    @user_wallet = UserWallet.where(:user_id => @operations_status.user_id).first
    @user_balance = @user_wallet.amount
    @bank = CompanyBank.where(:bank_key => @operations_status.payment_gateway).first
    @original_amount = (((@operations_status.amount.to_f - @bank.fees) * 100 )/(@bank.ratio + 100))
    @user = User.where("id = ?", @operations_status.user_id.to_i).first
    @user_notification_setting = NotificationsSetting.where(user_id: @operations_status.user_id).first

    if @operations_status.status ==  0
      @operations_status.update(:status => 1)
      @operation_card.update(:status => 2)
      @user_new_balance = @user_balance + @original_amount.to_f
      @user_wallet.update(:amount => @user_new_balance)
      @smstext = "Your #{@original_amount} USD payers card has been confirmed and added to your wallet by admin"
      Notification.create(user_id: @operations_status.user_id ,title: "Recharge Wallet Balance", description: @smstext , notification_type: @user_notification_setting.money_transactions)
   
      if @user_notification_setting.money_transactions == 3
        SMSNotification.sms_notification_setting(@user.telephone,@smstext)
        SmsLog.create(:user_id => @user.id, :pinid => @smstext,:status => 1,:sms_type => 3)
        EmailNotification.email_notification_setting(user_mail:@user.email,subject:'Recharge Wallet Balance',text:@smstext)
      elsif @user_notification_setting.money_transactions == 2
        SMSNotification.sms_notification_setting(@user.telephone,@smstext)
        SmsLog.create(:user_id => @user.id, :pinid => @smstext,:status => 1,:sms_type => 3)
      elsif @user_notification_setting.money_transactions == 1
        EmailNotification.email_notification_setting(user_mail:@user.email,subject:'Recharge Wallet Balance',text:@smstext)
      end
      redirect_to(money_ops_path,:notice => 'Operation status was successfully updated to be Compeleted')
    elsif @operations_status.status ==  1
      @operations_status.update(:status => 0)
      @operation_card.update(:status => 3)
      @user_new_balance = @user_balance - @original_amount.to_f
      @user_wallet.update(:amount => @user_new_balance)
      @smstext = "Your #{@original_amount} USD payers card has been cancelled and removed from your wallet by admin"
      Notification.create(user_id: @operations_status.user_id ,title: "Recharge Wallet Balance", description: @smstext , notification_type: @user_notification_setting.money_transactions)
   
      if @user_notification_setting.money_transactions == 3
        SMSNotification.sms_notification_setting(@user.telephone,@smstext)
        SmsLog.create(:user_id => @user.id, :pinid => @smstext,:status => 1,:sms_type => 3)
        EmailNotification.email_notification_setting(user_mail:@user.email,subject:'Recharge Wallet Balance',text:@smstext)
      elsif @user_notification_setting.money_transactions == 2
        SMSNotification.sms_notification_setting(@user.telephone,@smstext)
        SmsLog.create(:user_id => @user.id, :pinid => @smstext,:status => 1,:sms_type => 3)
      elsif @user_notification_setting.money_transactions == 1
        EmailNotification.email_notification_setting(user_mail:@user.email,subject:'Recharge Wallet Balance',text:@smstext)
      end
      redirect_to(money_ops_path,:notice => 'Operation status was successfully updated to be Pending')
    else
      redirect_to(money_ops_path,:notice => 'Sorry, something went wrong')
    end

  end

  def remittance_operations
    @operations = MoneyOp.joins("INNER JOIN cards ON cards.operation_id = money_ops.opid").select("cards.number,cards.status,money_ops.user_id,money_ops.opid,money_ops.amount,money_ops.fees,money_ops.payment_gateway,money_ops.payment_date,money_ops.id").all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_money_op
      @money_op = MoneyOp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def money_op_params
      params.require(:money_op).permit(:opid, :optype, :amount, :fees, :payment_gateway, :status, :payment_date, :payment_id, :user_id , :admin_note)
    end
end

app/views/money_ops/_form.html.erb
<%= form_with(model: money_op, local: true) do |form| %>
  <% if money_op.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(money_op.errors.count, "error") %> prohibited this money_op from being saved:</h2>

      <ul>
      <% money_op.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :optype,options_for_select([['Wallet transfer',1],['Receive',2],['Withdraw',3],['Remittance',4]]),  {:include_blank => 'select type'} %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :payment_gateway %>
    <%= form.number_field :payment_gateway %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status,options_for_select([['Pending',0],['Compeleted',1]]),  {:include_blank => 'select status'} %>
  </div>

  <div class="field">
    <%= form.label :payment_date %>
    <%= form.datetime_select :payment_date %>
  </div>

  <div class="field">
    <%= form.label :paymentid %>
    <%= form.number_field :payment_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/money_ops/index.html.erb
<div class="padding">
  <div class="box">
    <div class="box-header">
      <h2>Money Operartions</h2>
      <small>List of all money operartions</small>
    </div>
    <div class="box-body">
      Search: <input id="filter" type="text" class="form-control input-sm w-auto inline m-r"/>
      <% if current_user and current_user.roleid == 1 %>
           <%= link_to 'New Money Op', new_money_op_path, {:class => 'btn btn-fw accent',:style => "margin-left:800px;"}%>
      <% end %>
    </div>
    <div>
      <table class="table m-b-none" ui-jp="footable" data-filter="#filter" data-page-size="5">
        <thead>
          <tr>
              <th>User id</th>
              <th>UserName</th>
              <th>Operartion id</th>
              <th>Type</th>
              <th>Amount</th>
              <th>Fees</th>
              <th>Payment gateway</th>
              <th data-hide="phone">Status</th>
              <th>Payment date</th>

          </tr>
        </thead>
        <tbody>
        <% @money_ops.each do |money_op| %>
          <tr>
          <td><%= money_op.user_id %></td>
          <td><%= money_op.user.firstname + " " + money_op.user.lastname %></td>
          <td><%= money_op.opid %></td>
          <% if money_op.optype == 1 %>
          <td><%= "Wallet transfer" %></td>
          <% elsif money_op.optype == 2 %>
          <td><%= "Receive" %></td>
          <% elsif money_op.optype == 3 %>
          <td><%= "Withdraw" %></td>
          <% elsif money_op.optype == 4 %>
          <td><%= "Remittance" %></td>
          <% end %>
          <% if money_op.amount != nil %>
          <td><%= money_op.amount.round(2) %></td>
          <% else %>
          <td><%= "-" %></td>
          <% end %>
          <% if money_op.fees != nil %>
          <td><%= money_op.fees.round(2) %></td>
          <% else %>
          <td><%= "-" %></td>
          <% end %>
          <td><%= money_op.payment_gateway %></td>
          <% if money_op.status == 0 %>
          <td data-value="3"><span class="label" title="Disabled">Pending</span></td>
          <% elsif money_op.status == 1 %>
          <td data-value="2"><span class="label success" title="Active">Compeleted</span></td>
          <% elsif money_op.status == 2 %>
          <td data-value="1"><span class="label" title="Disabled">Cancelled</span></td>
          <% end %>
          <td><%= money_op.payment_date %></td>
          <% if money_op.status == 0 %>
          <td><a href="/operations_status?id=<%= money_op.id %>" class="btn btn-primary">Update to Compeleted</a></td>
          <% elsif money_op.status == 1 %>
          <td><a href="/operations_status?id=<%= money_op.id %>" class="btn btn-warning">Update to Pending</a></td>
          <% else %>
          <td><%= "-" %></td>
          <% end %>
          <td><%= link_to 'Show', money_op %></td>
              
          </tr>
          <% end %>
          
        </tbody>
        <tfoot class="hide-if-no-paging">
          <tr>
              <td colspan="5" class="text-center">
                  <ul class="pagination"></ul>
              </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

app/views/money_ops/remittance_operations.html.erb
<div class="padding">
  <div class="box">
    <div class="box-header">
      <h2>Remittance Operartions</h2>
      <small>List of all remittance operartions</small>
    </div>
    <div class="box-body">
      Search: <input id="filter" type="text" class="form-control input-sm w-auto inline m-r"/>
      <%= link_to 'New Card', new_card_path, {:class => 'btn btn-fw accent',:style => "margin-left:800px;"}%>
    </div>
    <div>
      <table class="table m-b-none" ui-jp="footable" data-filter="#filter" data-page-size="5">
        <thead>
          <tr>
              <th>User id</th>
              <th>UserName</th>
              <th>Operartion id</th>
              <th>Card Num</th>
              <th>Amount</th>
              <th>Fees</th>
              <th>Payment gateway</th>
              <th data-hide="phone">Status</th>
              <th>Payment date</th>
              <th colspan="1"></th>

          </tr>
        </thead>
        <tbody>
        <% @operations.each do |operation| %>
          <tr>
          <td><%= operation.user_id %></td>
          <td><%= operation.user.firstname + " " + operation.user.lastname %></td>
          <td><%= operation.opid %></td>
          <% if operation.status == 3 %>
          <td><%= "****-****-****-****" %></td>
          <% else %>
          <td><%= operation.number.scan(/.{1,4}/).join('-') %></td>
          <% end %>
          <td><%= operation.amount %></td>
          <td><%= operation.fees %></td>
          <td><%= operation.payment_gateway %></td>
          <% if operation.status == 1 %>
          <td><span class="label success" title="Active">Active</span></td>
          <% elsif operation.status == 2 %>
          <td><span class="label success" title="Active">Charged</span></td>
          <% elsif operation.status == 3 %>
              <td><span class="label" title="Disabled">Pending</span></td>
          <% elsif operation.status == 4 %>
              <td><span class="label" title="Disabled">Cancelled</span></td>
          <% end %>
          <td><%= operation.payment_date %></td>
          <td><%= link_to 'Show', operation %></td>
              
          </tr>
          <% end %>
          
        </tbody>
        <tfoot class="hide-if-no-paging">
          <tr>
              <td colspan="5" class="text-center">
                  <ul class="pagination"></ul>
              </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

app/views/money_ops/show.html.erb
<div class="padding">
  
      <div class="box">
        <div class="box-header">
          <h3>Money Operation</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>UserName</th>
              <td><%= @money_op.user.firstname + " " + @money_op.user.lastname  %></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>User ID</th>
              <td> <%= @money_op.user_id %></td>
          </tr>
          <tr>
              <th>Operaion ID</th>
              <td><%= @money_op.opid %></td>
          </tr>
          <tr>
          <th>Operaion Type</th>
          <% if @money_op.optype == 1 %>
          <td><%= "Wallet transfer" %></td>
          <% elsif @money_op.optype == 2 %>
          <td><%= "Receive" %></td>
          <% elsif @money_op.optype == 3 %>
          <td><%= "Withdraw" %></td>
          <% elsif @money_op.optype == 4 %>
          <td><%= "Remittance" %></td>
          <% end %>
          </tr>
          <tr>
            <th>Amount</th>
            <td>  <% if @money_op.amount != nil %>
            <%= @money_op.amount.round(2) %>
            <% else %>
            <%= "-" %>
            <% end %></td>
          </tr>
          <tr>
            <th>Fees</th>
            <td>  <% if @money_op.fees != nil %>
            <%= @money_op.fees.round(2) %>
            <% else %>
            <%= "-" %>
            <% end %></td>
          </tr>
          <tr>
            <th>Payment Gateway</th>
            <td> <%= @money_op.payment_gateway %></td>
          </tr>
          <tr>
          <th>Status</th>
            <% if @money_op.status == 0 %>
            <td><span class="label"><%= "Pending" %></span></td>
            <% elsif @money_op.status == 1 %>
            <td><span class="label success"><%= "Compeleted" %></span></td>
            <% elsif @money_op.status == 2 %>
            <td><span class="label"><%= "Cancelled" %></span></td>
            <% end %>
          </tr>
          <tr>
            <th>Payment Date</th>
            <td><%= @money_op.payment_date %></td>
          </tr>
          <% if @money_op.payment_id != nil %> 
          <tr>
            <th>Payment ID</th>
            <td><%= @money_op.payment_id %></td>
          </tr>
          <% end %>
          <% if @bank_type == "local_bank" %>
            <% if @remittance_data.user_account_number != nil %>
              <tr>
                <th>Bank Account Number</th>
                <td><%= @remittance_data.user_account_number %></td>
              </tr>
            <% end %>

            <% if @remittance_data.note != nil %>
              <tr>
                <th>Note</th>
                <td><%= @remittance_data.note %></td>
              </tr>
            <% end %>

            <% if @remittance_data.payment_receipt.attached? %>
              <tr>
                <th>Attachment</th>
                <td><%= link_to image_tag(@remittance_data.payment_receipt.variant(resize: "100x100")),@remittance_data.payment_receipt %></td>
              </tr>
            <% end %>
          <% end %>

          <% if @money_op.admin_note != nil %>
          <tr>
            <th>Admin Note</th>
            <td><%= @money_op.admin_note %></td>
          </tr>
          <% end %>
          </tbody>
        </table>
     
      <% if (@money_op.optype == 3 || @money_op.optype == 4) && @money_op.status == 0 %>
        <div class="box-body">
            <%= form_for :admin_add_note ,:url => admin_add_note_path,:html => { :multipart => true } do |f| %>
                    <%=  f.hidden_field :operation_id, :value => @money_op.opid %>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">Send Note To User</label>
                        <div class="col-sm-10">
                            <%= f.text_area :admin_note , class: 'form-control' , :required => true %>
                        </div>
                    </div>

                  <div class="form-group row m-t-md">
                      <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-fw primary" id="submit" >Submit</button>
                      </div>
                  </div>
            <% end %>
        </div>
      <% end %>
      </div>
      <%= link_to 'Back', money_ops_path %>
      
</div>